#!/usr/bin/env bash
# lib/uninstall.sh — `watchman uninstall` (zero-token bash; no Claude, no git).
#
# The destructive inverse of install.sh: it unlinks the CLI, then removes the
# artifacts install created — in tiers, each behind its own confirmation. It is
# OPERATOR-RUN with explicit intent, so unlike the loop it CAN stop-warn-ask, and
# it does, for every removal.
#
# > PRIME DIRECTIVE. Uninstalling IS destructive — it deletes files irreversibly.
# > So this script obeys the directive to the letter: it STOPS before each class of
# > removal, WARNS in plain language what would be lost, and ASKS for explicit
# > per-tier consent (default NO; a non-interactive shell with no --yes refuses
# > rather than assume yes). It NEVER removes packages (other software may depend on
# > them — it only names them so you can remove them yourself), and it NEVER does a
# > blind `rm -rf` of the install directory: claude-watchman may be a guest inside a
# > host repo, so it deletes only the files IT owns (the manifest product + its own
# > generated artifacts) and hands the final directory delete back to you. It is the
# > one shell verb whose whole job is destruction, which is exactly why every step
# > is gated.

_UN_LINK="${WATCHMAN_LINK:-/usr/local/bin/watchman}"
_un_assume_yes=no

_un_say()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
_un_warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*" >&2; }
_un_del()  { printf '  \033[1;31m[removed]\033[0m %s\n' "$*"; }
_un_keep() { printf '  \033[2m[kept]\033[0m %s\n' "$*"; }

# Mirror install.sh's confirm(): default NO, and a non-interactive shell with no
# --yes REFUSES (fail safe) rather than silently deleting.
_un_confirm() {
    [[ "$_un_assume_yes" == yes ]] && return 0
    [[ -t 0 ]] || { _un_warn "non-interactive shell — refusing (answer 'no'): $1"; return 1; }
    local reply
    read -r -p "    $1 [y/N] " reply
    [[ "$reply" =~ ^[Yy]$ ]]
}

# Remove a single path (file, dir, or dangling symlink) and report it, relative to
# the install root for readable output. No-op if it does not exist.
_un_rm() {
    local p="$1" root="$2"
    if [[ -e "$p" || -L "$p" ]]; then
        rm -rf -- "$p" && _un_del "${p#"$root"/}"
    fi
}

# Remove every path matching the given glob(s) under the install root.
_un_rm_glob() {
    local root="$1"; shift
    local pat g
    for pat in "$@"; do
        while IFS= read -r g; do
            [[ -n "$g" ]] && _un_rm "$g" "$root"
        done < <(compgen -G "$root/$pat" 2>/dev/null || true)
    done
}

uninstall_run() {
    local root="$WATCHMAN_ROOT"
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --yes|-y) _un_assume_yes=yes ;;
            *) echo "uninstall: unknown arg '$1' (only --yes is accepted)" >&2; return 2 ;;
        esac
        shift
    done

    [[ -d "$root" ]] || { _un_warn "WATCHMAN_ROOT ($root) does not exist — nothing to uninstall."; return 0; }

    _un_say "claude-watchman uninstall — install root: $root"
    cat >&2 <<EOF

This removes claude-watchman in tiers, asking before each one (default is No). It will:
  * NOT remove packages — sqlite3, jq, msmtp, lynis (and crowdsec, if installed) are
    left in place; other software may use them. Remove them yourself if you want.
  * NOT delete the install directory wholesale — it removes only the files watchman
    owns, then tells you the directory is yours to delete if you want it gone.
EOF

    # --- Tier 1: the CLI symlink -------------------------------------------
    # Only touch /usr/local/bin/watchman if it is a symlink resolving to THIS
    # install's bin/watchman — never remove an unrelated file at that path.
    _un_say "1. CLI symlink ($_UN_LINK)"
    if [[ -L "$_UN_LINK" ]]; then
        local tgt="" want=""
        command -v readlink >/dev/null 2>&1 && tgt="$(readlink -f "$_UN_LINK" 2>/dev/null || true)"
        want="$(readlink -f "$root/bin/watchman" 2>/dev/null || echo "$root/bin/watchman")"
        if [[ "$tgt" == "$want" ]]; then
            if _un_confirm "Remove the symlink $_UN_LINK -> $want?"; then
                _un_rm "$_UN_LINK" "$root"
            else
                _un_keep "$_UN_LINK"
            fi
        else
            _un_warn "$_UN_LINK points to '$tgt', not this install — leaving it untouched."
        fi
    elif [[ -e "$_UN_LINK" ]]; then
        _un_warn "$_UN_LINK exists but is not a symlink — leaving it untouched."
    else
        _un_keep "$_UN_LINK (absent)"
    fi

    # --- Tier 2: regenerable local artifacts -------------------------------
    # The Claude permission profiles + deployed command, and preflight scratch.
    # All of this is regenerated by `watchman preflight`, so losing it is cheap.
    _un_say "2. Generated local artifacts (.claude/, preflight scratch, journal backups)"
    if _un_confirm "Remove the regenerable artifacts (regenerated by 'watchman preflight')?"; then
        _un_rm "$root/.claude" "$root"
        _un_rm_glob "$root" ".pf.allow" ".pf.dirs" ".pf.sudoers" ".pf.fix.allow" ".pf.fix.dirs" \
                    ".watchman-sudoers.staged" "journal/findings.db.backup-*"
    else
        _un_keep "generated artifacts"
    fi

    # --- Tier 3: operator DATA and SECRETS (loud) --------------------------
    # The irreversible tier: .env holds your SMTP password; findings.db is the
    # entire journal history; the baselines/offsets are accumulated state.
    _un_say "3. Operator data & secrets (.env, config, journal database, baselines)"
    _un_warn "DESTRUCTIVE & IRREVERSIBLE: this deletes your SMTP credentials (.env), your"
    _un_warn "machine config, and the ENTIRE finding history in journal/findings.db. There"
    _un_warn "is no backup and no undo. Skip this tier to keep your data if you may reinstall."
    if _un_confirm "Permanently delete .env, config, and the journal database?"; then
        _un_rm "$root/.env" "$root"
        _un_rm "$root/config/watchman.conf" "$root"
        _un_rm_glob "$root" "journal/findings.db" "journal/findings.db-wal" "journal/findings.db-shm" \
                    "journal/network-baseline.txt" "journal/log-offsets.txt" "journal/.write.lock"
    else
        _un_keep "operator data & secrets"
    fi

    # --- Tier 4: the product code ------------------------------------------
    # Remove exactly the files the manifest shipped (read the manifest in full
    # first, since it lists files we are about to delete), plus manifest.txt
    # itself. .gitignore is intentionally NOT touched (install.sh only APPENDED a
    # block to it, and it may be a host repo's file) — we point it out at the end.
    _un_say "4. Product code (skills/, lib/, commands/, bin/, install.sh, …)"
    if _un_confirm "Remove the claude-watchman product files from $root?"; then
        local -a product=()
        if [[ -f "$root/manifest.txt" ]]; then
            local line
            while IFS= read -r line || [[ -n "$line" ]]; do
                case "$line" in ''|\#*) continue ;; esac
                line="${line#hook }"; line="${line#keep }"
                product+=("$line")
            done < "$root/manifest.txt"
        else
            _un_warn "manifest.txt missing — falling back to the known product directories."
            product=(bin/watchman install.sh journal/schema.sql .env.example
                     config/watchman.conf.example commands/watchman/SKILL.md skills/MANIFEST.md)
        fi
        local p
        for p in "${product[@]}"; do _un_rm "$root/$p" "$root"; done
        _un_rm "$root/manifest.txt" "$root"
        # Prune empty dirs ONLY within watchman's own subtrees (never $root, never
        # host dirs). -empty -delete is a no-op on any dir that still holds data.
        local d
        for d in skills lib commands config journal bin; do
            [[ -d "$root/$d" ]] && find "$root/$d" -type d -empty -delete 2>/dev/null || true
        done
    else
        _un_keep "product code"
    fi

    # --- Wrap up ------------------------------------------------------------
    _un_say "Uninstall steps complete."
    cat >&2 <<EOF

Left in place on purpose:
  * Packages (sqlite3, jq, msmtp, lynis, and crowdsec if present). Remove with your
    package manager if nothing else needs them.
EOF
    [[ -f "$root/.gitignore" ]] && grep -q 'claude-watchman — never commit these' "$root/.gitignore" 2>/dev/null \
        && _un_warn ".gitignore still carries the claude-watchman block — remove that block by hand if you want it gone."
    [[ -f "$root/CLAUDE.md" ]] \
        && _un_warn "CLAUDE.md (development standing-context, gitignored) is still here — delete it by hand if unwanted."

    if find "$root" -mindepth 1 -print -quit 2>/dev/null | grep -q .; then
        cat >&2 <<EOF

The install directory still holds files (kept data, the host repo, or your own
content). claude-watchman never deletes the directory wholesale. If this was a
dedicated watchman directory and you want it gone entirely, you can remove it
yourself:
    rm -rf "$root"
EOF
    else
        _un_say "Install directory $root is now empty — 'rmdir \"$root\"' to remove it."
    fi
}
